apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-spring-app-deployment
spec:
  selector:
    matchLabels:
      app: kube-spring-app
  template:
    metadata:
      labels:
        app: kube-spring-app
    spec:
      containers:
        - name: kube-spring-app
          image: kimmyungjin/kube-spring-app # 사용하고자 하는 이미지
          ports:
            - containerPort: 8080 # 컨테이너가 사용하는 포트