apiVersion: v1
kind: Service
metadata:
  name: kube-spring-app-service
spec:
  selector:
    app: kube-spring-app
  ports:
    - protocol: TCP
      port: 80       # Service 포트
      targetPort: 8080 # Pod의 컨테이너 포트
  type: ClusterIP