apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deploy-patch.yaml
  target:
    kind: Deployment
    name: kube-spring-app-deployment

images:
- name: kimmyungjin/kube-spring-app
  newName: kimmyungjin/kube-spring-app
  newTag: "4"
