apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-spring-app
  labels:
    app: kube-spring-app
spec:
  replicas: 2 # 생성할 Pod의 복제본 수
  revisionHistoryLimit: 3 # 레플리카셋 관리를 위한 리비전 기록 수
  selector:
    matchLabels:
      app: kube-spring-app
  template:
    metadata:
      labels:
        app: kube-spring-app
    spec:
      containers:
        - name: kube-spring-app
          image: kimmyungjin/kube-spring-app:4 # 사용하고자 하는 이미지
          ports:
            - containerPort: 8080 # 컨테이너가 사용하는 포트