apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-spring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DOIF-Dobby/kube-manifests'
    targetRevision: main
    path: manifests/kube-spring-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
      rollback:
        enabled: true
