apiVersion: v1
kind: Service
metadata:
  name: kube-front-app-service
spec:
  selector:
    app: kube-front-app
  ports:
    - protocol: TCP
      port: 80       # Service 포트
      targetPort: 3000 # 컨테이너 포트
  type: ClusterIP